
language: cpp

matrix:
    include:
        - os: osx
          osx_image: xcode8
          compiler:
              - clang

          before_install:
              - ./ci/install_deps_osx.sh

          cache:
              directories:
                  - $HOME/Library/Caches/Homebrew
          script: ./ci/clang-format.sh
          script: ./build.py

        - os: linux
          dist: xenial
          before_install:
              - sudo apt-get -qq update
              - sudo apt-get install -y cmake libsdl2-dev libsdl2-ttf-dev liblua5.2-dev libboost-system-dev libboost-filesystem-dev
          script: ./ci/clang-format.sh
          script: ./build.py
